config/routes.rb
AgileIbooks::Application.routes.draw do

  resources :compromises

  resources :theses

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "student/index", :as => 'student'
  get "adviser/index", :as => 'adviser'

  get "artefacts" => "artefacts#index"
  
  resources :users
  resources :sessions
  
  resources :images do
    member do
      get :decouple
      get :download
    end
  end
  
  resources :videos do
    member do
      get :decouple
      get :download
    end
  end

  resources :audios do
    member do
      get :decouple
      get :download
    end
  end

  resources :reunions do 
    get "artefacts" => "artefacts#index"
  end

  root :to => "users#index"












end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :description, :title, :video

  validates :video, :description, :title, :presence => true

  validates :video, :format => {
	:with => %r{\.(3gp)$}i,
	:message => 'must be a 3GP.'
  }

  belongs_to :reunion

  mount_uploader :video, VideoUploader
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    @video.reunion_id = session[:reunion_id]

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  def decouple
    @video = Video.find(params[:id])
    @video.reunion_id = nil
    respond_to do |format|
      if @video.save
        format.html { redirect_to artefacts_path, notice: 'Video was successfully decoupled.' }
      else
        format.html { render action: "index" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def download
    @video = Video.find(params[:id])
    send_file Rails.root.join("public"+@video.video_url)
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :video %><br />
    <%= f.file_field :video %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video, :class => 'btn btn-small' %> |
<%= link_to 'Back', videos_path, :class => 'btn btn-small' %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table class='table table-striped table-bordered table-condensed'>
  <tr>
    <th>Title</th>
    <th>Video</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.title %></td>
    <td><%= video.video %></td>
    <td><%= video.description %></td>
    <td><%= link_to 'Show', video, :class => 'btn btn-small' %></td>
    <td><%= link_to 'Edit', edit_video_path(video), :class => 'btn btn-small' %></td>
    <td><%= link_to 'Destroy', video, method: :delete, :class => 'btn btn-small', data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video', new_video_path, :class => 'btn btn-primary' %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path, :class => 'btn btn-small' %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @video.title %>
</p>

<!-- <p>
  <b>Video:</b>
  <%= @video.video %>
</p> -->

<video controls width="640" height="450" poster="/uploads/video/sample.png">
	<source src="<%= @video.video_url.to_s %>" >
	<object width="640" height="450" type="application/x-shockwave-flash" data="player.swf">
		<param name="movie" value="player.swf">
		<param name="flashvars" value="controlbar=over&amp;image=/uploads/video/sample.png&amp;file=<%= @video.video_url.to_s %>">
		<img src="/uploads/video/sample.png" width="640" height="360" alt="Sample" title="No direct video playback capabilities, so please download the video below">
	</object>
</video>

<p>
  <b>Description:</b>
  <%= @video.description %>
</p>


<%= link_to 'Edit', edit_video_path(@video), :class => 'btn btn-small' %> |
<%= link_to 'Back', videos_path, :class => 'btn btn-small' %>