config/routes.rb
AgileIbooks::Application.routes.draw do

  resources :compromises

  resources :theses

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "student/index", :as => 'student'
  get "adviser/index", :as => 'adviser'

  get "artefacts" => "artefacts#index"
  
  resources :users
  resources :sessions
  
  resources :images do
    member do
      get :decouple
      get :download
    end
  end
  
  resources :videos do
    member do
      get :decouple
      get :download
    end
  end

  resources :audios do
    member do
      get :decouple
      get :download
    end
  end

  resources :reunions do 
    get "artefacts" => "artefacts#index"
  end

  root :to => "users#index"












end

app/models/reunion.rb
class Reunion < ActiveRecord::Base
  attr_accessible :date, :duration, :place, :subject
  validates :date, :duration, :place, :subject, :presence => true
  has_many :images, :dependent => :destroy
  has_many :videos, :dependent => :destroy
  has_many :audios, :dependent => :destroy
end

app/controllers/reunions_controller.rb
class ReunionsController < ApplicationController
  before_filter :require_login
  # GET /reunions
  # GET /reunions.json
  
  def index
    @user = User.find(session[:user_id])
    
    if @user.rol == 1
      redirect_to student_path
    elsif @user.rol == 2
      @reunions = Reunion.all
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @reunions }
      end
    end
  end

  # GET /reunions/1
  # GET /reunions/1.json
  def show
    @reunion = Reunion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reunion }
    end
  end

  # GET /reunions/new
  # GET /reunions/new.json
  def new
    @reunion = Reunion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reunion }
    end
  end

  # GET /reunions/1/edit
  def edit
    @reunion = Reunion.find(params[:id])
  end

  # POST /reunions
  # POST /reunions.json
  def create
    @reunion = Reunion.new(params[:reunion])

    respond_to do |format|
      if @reunion.save
        format.html { redirect_to @reunion, notice: 'Reunion was successfully created.' }
        format.json { render json: @reunion, status: :created, location: @reunion }
      else
        format.html { render action: "new" }
        format.json { render json: @reunion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reunions/1
  # PUT /reunions/1.json
  def update
    @reunion = Reunion.find(params[:id])

    respond_to do |format|
      if @reunion.update_attributes(params[:reunion])
        format.html { redirect_to @reunion, notice: 'Reunion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reunion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reunions/1
  # DELETE /reunions/1.json
  def destroy
    @reunion = Reunion.find(params[:id])
    @reunion.destroy

    respond_to do |format|
      format.html { redirect_to reunions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reunions_helper.rb
module ReunionsHelper
end

app/views/reunions/_form.html.erb
<%= form_for(@reunion) do |f| %>
  <% if @reunion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reunion.errors.count, "error") %> prohibited this reunion from being saved:</h2>

      <ul>
      <% @reunion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :duration %>
    <%= f.time_select :duration %>
  </div>
  <div class="field">
    <%= f.label :place %>
    <%= f.text_field :place %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reunions/edit.html.erb
<h1>Editing reunion</h1>

<%= render 'form' %>

<%= link_to 'Show', @reunion, :class => 'btn btn-small' %> |
<%= link_to 'Back', reunions_path, :class => 'btn btn-small' %>

app/views/reunions/index.html.erb
<h1>Listing reunions</h1>

<table class='table table-striped table-bordered table-condensed'>
  <tr>
    <th>Date</th>
    <th>Subject</th>
    <th>Duration</th>
    <th>Place</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reunions.each do |reunion| %>
  <tr>
    <td><%= reunion.date %></td>
    <td><%= reunion.subject %></td>
    <td><%= reunion.duration %></td>
    <td><%= reunion.place %></td>
    <td><%= link_to 'Add Artefact', artefacts_path(:reunion_id => reunion), :class => 'btn btn-small btn-success'  %></td>
    <td><%= link_to 'Add Compromises', compromises_path(:reunion_id => reunion), :class => 'btn btn-small btn-success'  %></td>
    <td><%= link_to 'Show', reunion, :class => 'btn btn-small'  %></td>
    <td><%= link_to 'Edit', edit_reunion_path(reunion), :class => 'btn btn-small'  %></td>
    <td><%= link_to 'Destroy', reunion, method: :delete, :class => 'btn btn-small', data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reunion', new_reunion_path, :class => 'btn btn-primary' %>

app/views/reunions/new.html.erb
<h1>New reunion</h1>

<%= render 'form' %>

<%= link_to 'Back', reunions_path, :class => 'btn btn-small' %>

app/views/reunions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @reunion.date %>
</p>

<p>
  <b>Subject:</b>
  <%= @reunion.subject %>
</p>

<p>
  <b>Duration:</b>
  <%= @reunion.duration %>
</p>

<p>
  <b>Place:</b>
  <%= @reunion.place %>
</p>


<%= link_to 'Edit', edit_reunion_path(@reunion), :class => 'btn btn-small' %> |
<%= link_to 'Back', reunions_path, :class => 'btn btn-small' %>