config/routes.rb
AgileIbooks::Application.routes.draw do

  resources :compromises

  resources :theses

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "student/index", :as => 'student'
  get "adviser/index", :as => 'adviser'

  get "artefacts" => "artefacts#index"
  
  resources :users
  resources :sessions
  
  resources :images do
    member do
      get :decouple
      get :download
    end
  end
  
  resources :videos do
    member do
      get :decouple
      get :download
    end
  end

  resources :audios do
    member do
      get :decouple
      get :download
    end
  end

  resources :reunions do 
    get "artefacts" => "artefacts#index"
  end

  root :to => "users#index"












end

app/models/adviser.rb
class Adviser < User
  attr_accessible :degree
  has_many :theses
end

app/models/audio.rb
class Audio < ActiveRecord::Base
  attr_accessible :audio, :description, :title

  validates :audio, :description, :title, :presence => true
  
  validates :audio, :format => {
	:with => %r{\.(mp3)$}i,
	:message => 'must be a MP3.'
  }

  belongs_to :reunion

  mount_uploader :audio, AudioUploader
end

app/models/compromise.rb
class Compromise < ActiveRecord::Base
  attr_accessible :date, :description, :reunion_id, :state

  validates :date, :description, :presence => true

  belongs_to :reunion
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :description, :image, :title
  
  validates :image, :description, :title, :presence => true

  validates :image, :format => {
	:with => %r{\.(jpg|png)$}i,
	:message => 'must be a JPEG or PNG.'
  }

  belongs_to :reunion
  
  mount_uploader :image, ImageUploader
end

app/models/reunion.rb
class Reunion < ActiveRecord::Base
  attr_accessible :date, :duration, :place, :subject
  validates :date, :duration, :place, :subject, :presence => true
  has_many :images, :dependent => :destroy
  has_many :videos, :dependent => :destroy
  has_many :audios, :dependent => :destroy
end

app/models/student.rb
class Student < User
  attr_accessible :career
end

app/models/thesis.rb
class Thesis < ActiveRecord::Base
  belongs_to :adviser
  attr_accessible :description, :title, :adviser
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  # attr_accessible :title, :body
  attr_accessible :username, :email, :password, :password_confirmation
 
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :description, :title, :video

  validates :video, :description, :title, :presence => true

  validates :video, :format => {
	:with => %r{\.(3gp)$}i,
	:message => 'must be a 3GP.'
  }

  belongs_to :reunion

  mount_uploader :video, VideoUploader
end

app/controllers/artefacts_controller.rb
class ArtefactsController < ApplicationController
  before_filter :require_login
  
  def index
    @user = current_user
    
    if session[:reunion_id] == nil
      @reunion = Reunion.find(params[:reunion_id])
      session[:reunion_id] = @reunion.id
    elsif
      @reunion = Reunion.find(session[:reunion_id])
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reunion }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Usuario registrado!"
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/adviser_helper.rb
module AdviserHelper
end

app/helpers/artefacts_helper.rb
module ArtefactsHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/compromises_helper.rb
module CompromisesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/reunions_helper.rb
module ReunionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/theses_helper.rb
module ThesesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/artefacts/index.html.erb
<h1>Add Artefact to Reunion </h1>

<p id="notice"><%= notice %></p>

<table class='table table-striped table-bordered table-condensed'>
  <tr>
    <th>Date</th>
    <th>Subject</th>
    <th>Place</th>
  </tr>

  <tr>
    <td><%= @reunion.date %></td>
    <td><%= @reunion.subject %></td>
    <td><%= @reunion.place %></td>
  </tr>
</table>


<h2>Artefacts</h2>
<!-- <select class="control-group" id="artefact_type" name="artefact_type"> 
   <option value="0">Select the type of artefact</option> 
   <option value="1">Image</option> 
   <option value="2">Audio</option> 
   <option value="3">Video</option> 
</select> 

<br /> -->

<h3>Images</h3>
<% if @reunion.images.size == 0%>
	<h4>La reunión no tiene imágenes asociadas</h4>
<% elsif @reunion.images.size > 0%>
	<table class='table table-striped table-condensed'>
		<tr>
    		<th>Title</th>
    		<th>Options</th>
		</tr>

		<% @reunion.images.each do |image| %>
			<tr>
    			<td><%= image.title %></td>
    			<td><%= link_to 'Show', image, :class => 'btn btn-small' %>
    				<%= link_to "Decouple", decouple_image_path(image), :class => 'btn btn-small', data: { confirm: 'Are you sure?' } %>
            <%= link_to 'Download', download_image_path(image) %>
          </td>
    		</tr>
    	<% end %>

	</table>
<% end %>
<%= link_to 'Add new Image', new_image_path, :class => 'btn btn-primary' %>


<h3>Audios</h3>
<% if @reunion.audios.size == 0%>
	<h4>La reunión no tiene audios asociados</h4>
<% elsif @reunion.audios.size > 0%>
	<table class='table table-striped table-condensed'>
		<tr>
    		<th>Title</th>
    		<th>Options</th>
		</tr>
		<% @reunion.audios.each do |audio| %>
			<tr>
    			<td><%= audio.title %></td>
    			<td><%= link_to 'Show', audio, :class => 'btn btn-small' %>
    			    <%= link_to "Decouple", decouple_audio_path(audio), :class => 'btn btn-small', data: { confirm: 'Are you sure?' } %>
              <%= link_to 'Download', download_audio_path(audio) %>
          </td>
    		</tr>
    	<% end %>
	</table>
<% end %>
<%= link_to 'Add new Audio', new_audio_path, :class => 'btn btn-primary' %>


<h3>Videos</h3>
<% if @reunion.videos.size == 0%>
	<h4>La reunión no tiene videos asociados</h4>
<% elsif @reunion.videos.size > 0%>
	<table class='table table-striped table-condensed'>
		<tr>
    		<th>Title</th>
    		<th>Options</th>
		</tr>
		<% @reunion.videos.each do |video| %>
			<tr>
    			<td><%= video.title %></td>
    			<td><%= link_to 'Show', video, :class => 'btn btn-small' %>
    			    <%= link_to "Decouple", decouple_video_path(video), :class => 'btn btn-small', data: { confirm: 'Are you sure?' } %>
              <%= link_to 'Download', download_video_path(video) %>	
          </td>
    		</tr>
    	<% end %>
	</table>
<% end %>
<%= link_to 'Add new Video', new_video_path, :class => 'btn btn-primary' %>