config/routes.rb
AgileIbooks::Application.routes.draw do

  resources :compromises

  resources :theses

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "student/index", :as => 'student'
  get "adviser/index", :as => 'adviser'

  get "artefacts" => "artefacts#index"
  
  resources :users
  resources :sessions
  
  resources :images do
    member do
      get :decouple
      get :download
    end
  end
  
  resources :videos do
    member do
      get :decouple
      get :download
    end
  end

  resources :audios do
    member do
      get :decouple
      get :download
    end
  end

  resources :reunions do 
    get "artefacts" => "artefacts#index"
  end

  root :to => "users#index"












end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :description, :image, :title
  
  validates :image, :description, :title, :presence => true

  validates :image, :format => {
	:with => %r{\.(jpg|png)$}i,
	:message => 'must be a JPEG or PNG.'
  }

  belongs_to :reunion
  
  mount_uploader :image, ImageUploader
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # before_filter :require_login
  # GET /images
  # GET /images.json
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])

    @image.reunion_id = session[:reunion_id]

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  def decouple
    @image = Image.find(params[:id])
    @image.reunion_id = nil
    respond_to do |format|
      if @image.save
        format.html { redirect_to artefacts_path, notice: 'Image was successfully decoupled.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "index" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def download
    @image = Image.find(params[:id])
    send_file Rails.root.join("public"+@image.image_url)
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for (@image), :html => {:multipart => true} do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div><br />
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image, :class => 'btn btn-small' %> |
<%= link_to 'Back', images_path, :class => 'btn btn-small' %>

app/views/images/index.html.erb
<h3>Listing images</h3>

<table class='table table-striped table-bordered table-condensed'>
  <tr>
    <th>Title</th>
    <th>Image</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= image.title %></td>
    <td><%= image.image %></td>
    <td><%= image.description %></td>
    <td><%= link_to 'Show', image, :class => 'btn btn-small' %></td>
    <td><%= link_to 'Edit', edit_image_path(image), :class => 'btn btn-small' %></td>
    <td><%= link_to 'Destroy', image, method: :delete, :class => 'btn btn-small', data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image', new_image_path, :class => 'btn btn-primary' %>

app/views/images/new.html.erb
<h3>New image</h3>

<%= render 'form' %>

<%= link_to 'Back', images_path, :class => 'btn btn-small' %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @image.title %>
</p>

<div class="image">
  <%= image_tag @image.image_url(:thumb).to_s, :class => "style_image" %>
</div>

<p>
  <b>Description:</b>
  <%= @image.description %>
</p>


<%= link_to 'Edit', edit_image_path(@image), :class => 'btn btn-small' %> |
<%= link_to 'Back', images_path, :class => 'btn btn-small' %>